name: Deploy transformations
on:
  push:
    branches:
      - main
jobs:
  publish-dm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy transformations
        uses: cognitedata/transformations-cli@main
        env:
            # Credentials to be used when running your transformations,
            # as referenced in your manifests:
            COGNITE_CLIENT_ID: $CLI_CLIENT_ID
            COGNITE_CLIENT_SECRET: ${{ secrets.CLI_CLIENT_SECRET }}
        with:
            # Credentials used for deployment
            path: transformations  # Transformation manifest folder, relative to GITHUB_WORKSPACE
            client-id: $CLI_CLIENT_ID
            client-secret: ${{ secrets.CLI_CLIENT_SECRET }}
            token-url: https://login.microsoftonline.com/$CLI_TENANT/oauth2/v2.0/token
            cdf-project-name: $CLI_PROJECT
            # If you need to provide multiple scopes, the format: "scope1 scope2 scope3"
            scopes: https://$CLI_CLUSTER.cognitedata.com/.default
            # audience: "" # Optional